namespace: purestorage
name: common
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/purestorage.common.git
documentation: https://github.com/ansible-collection-migration/purestorage.common/tree/master/docs
homepage: https://github.com/ansible-collection-migration/purestorage.common
issues: https://github.com/ansible-collection-migration/purestorage.common/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
